version: "3.8"
services:
  # Symfony apache project container
  www:
    build: docker/php
    container_name: test_platinum
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - test_platinum

networks:
  test_platinum:
